name: flutter_embed_unity_example
description: Demonstrates how to use the flutter_embed_unity plugin.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_embed_unity: ^1.3.1
  intl: any
  http: ^1.2.0
  flutter_dotenv: ^6.0.0
  supabase_flutter: ^2.8.0
  flutter_secure_storage: ^9.0.0
  
  # Local Database - Isar
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.1
  
  # State Management - BLoC
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # Speech to Text
  speech_to_text: ^7.0.0
  permission_handler: ^11.0.1


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  
  # Isar code generation
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.6


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/

  fonts:
    - family: Alegreya
      fonts:
        - asset: assets/fonts/Alegreya-Regular.ttf
        - asset: assets/fonts/Alegreya-Medium.ttf
          weight: 500
        - asset: assets/fonts/Alegreya-Bold.ttf
          weight: 700
        - asset: assets/fonts/Alegreya-Italic.ttf
          style: italic
